<?php
/**
 * Billingcodes
 *
 * This class has been generated by ZeolIDE
 *
 * @author Equipo de desarrollo Linea Marco Trabajo
 * @version $Rev:$
 */
class BillingcodesModel extends ZendExt_Model {

    public function BillingcodesModel() {
        parent::ZendExt_Model();
    }

    public function adicionarBillingcodes($instance) {
        $instance->save();
        return true;
    }

    public function modificarBillingcodes($instance) {
        $instance->save();
        return true;
    }

    public function eliminarBillingcodes($instance) {
        $instance->delete();
        return true;
    }
}