<?php
/**
 * Grouppquota
 *
 * This class has been generated by ZeolIDE
 *
 * @author Equipo de desarrollo Linea Marco Trabajo
 * @version $Rev:$
 */
class GrouppquotaModel extends ZendExt_Model {

    public function GrouppquotaModel() {
        parent::ZendExt_Model();
    }

    public function adicionarGrouppquota($instance) {
        $instance->save();
        return true;
    }

    public function modificarGrouppquota($instance) {
        $instance->save();
        return true;
    }

    public function eliminarGrouppquota($instance) {
        $instance->delete();
        return true;
    }
}