<?php
/**
 * Printergroupsmembers
 *
 * This class has been generated by ZeolIDE
 *
 * @author Equipo de desarrollo Linea Marco Trabajo
 * @version $Rev:$
 */
class PrintergroupsmembersModel extends ZendExt_Model {

    public function PrintergroupsmembersModel() {
        parent::ZendExt_Model();
    }

    public function adicionarPrintergroupsmembers($instance) {
        $instance->save();
        return true;
    }

    public function modificarPrintergroupsmembers($instance) {
        $instance->save();
        return true;
    }

    public function eliminarPrintergroupsmembers($instance) {
        $instance->delete();
        return true;
    }
}