<?php
/**
 * Userpquota
 *
 * This class has been generated by ZeolIDE
 *
 * @author Equipo de desarrollo Linea Marco Trabajo
 * @version $Rev:$
 */
class UserpquotaModel extends ZendExt_Model {

    public function UserpquotaModel() {
        parent::ZendExt_Model();
    }

    public function adicionarUserpquota($instance) {
        $instance->save();
        return true;
    }

    public function modificarUserpquota($instance) {
        $instance->save();
        return true;
    }

    public function eliminarUserpquota($instance) {
        $instance->delete();
        return true;
    }
}