<?php
/**
 * Server
 *
 * This class has been generated by ZeolIDE
 *
 * @author Equipo de desarrollo Linea Marco Trabajo
 * @version $Rev:$
 */

class Server extends BaseServer
{
	public static function getAll() {
		$query = Doctrine_Query::Create();
      	$result = $query->select("s.denomination as text, s.active as checked, s.active as expanded, s.id")
                    ->from('Server s')
                    ->fetchArray();
      	return $result;
	}

    public function saveStatus($nodes){
        foreach($nodes as $val=>$node){
            if(count($node) > 0)
                Model_Query::create()
                    ->update('mod_pykota.server')
                    ->set('active', $val)
                    ->where(true)
                    ->whereIn('id', $node)
                    ->execute()
                ;
        }
    }
}