<!--
 * @author		Antonio Membrides Espinosa
 * @package    	simpresion
 * @date		21/06/2015
 * @copyright  	Copyright (c) 2015-2015 XETID
 * @license    	XETID
 * @version    	1.0
-->
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
        <title>Sistema MCSI</title>

<!-- tema 1 
        <link rel="stylesheet" type="text/css" href="/simpresion/css/ext-all-neptune-alt.css"/>
        <script type="text/javascript" src="/lib/adapters/ExtJS/4.1/js/ext-debug.js"></script>
-->
<!-- tema 2 -->
		<link href="/lib/adapters/ExtJS/4.1/css/ext-all-neptune.css" rel="stylesheet" type="text/css"/>
		<script src="/lib/adapters/ExtJS/4.1/resources/ext-all.js" type="text/javascript"></script>
		<script src="/lib/adapters/ExtJS/4.1/resources/ext-theme-neptune.js" type="text/javascript"></script>

		<link href="/simpresion/css/main.css" rel="stylesheet" type="text/css" />
        <link href="/simpresion/css/ace-fonts.css" rel="stylesheet" type="text/css" />
        <link href="/simpresion/css/font-awesome.min.css"rel="stylesheet" type="text/css" />
        
        <script> var idiom = {}; </script>
        <script  src="/simpresion/idioma/es/monitoreo.js" type="text/javascript"></script>
        <script  src="/simpresion/js/app.js" type="text/javascript"></script>
    </head>

    <body>  </body>
</html>
